add validation error

diff --git a/script/skip_build_if_ignored_paths b/script/skip_build_if_ignored_paths
--- a/script/skip_build_if_ignored_paths
+++ b/script/skip_build_if_ignored_paths
@@ -13,6 +13,16 @@
 
 set -e
 
+if [ -z "$GIT_BASE_REF" ]; then
+  echo "--> ENV var GIT_BASE_REF is required, bailing…"
+  exit 1
+fi
+
+if [ -z "$GIT_REF" ]; then
+  echo "--> ENV var GIT_REF is required, bailing…"
+  exit 1
+fi
+
 non_ignored_paths=$({
     find . -type f -o -type d -name .git -prune
 
